### ISSUE TITLE
Error Parsing Config

### ISSUE THREAD

**Issue by mctf-l-user** [mctf-codeninja/verifyme22#1]
I am unable to get the verify working. Why I attempt to run, I get the following error:

```
panic: Fatal error config file: While parsing config: invalid character '}' looking for beginning of object key string


goroutine 1 [running]:
main.main()
        /go/src/app/src/main.go:47 +0x3ae
```

**Comment by mctf-codeninja** [comment]
That error message suggests there is a problem with the formatting of your JSON configuration file. Please verify that your config is valid JSON. If you still think there's an error, post your config file here and I'll take a look.

**Comment by mctf-l-user** [comment]
My Javascript didn't have any issue parsing it.
[config.zip](https://github.com/mctf-codeninja/verifyme22/files/8508408/config.zip)

**Comment by mctf-codeninja** [comment]
Ah, there's a trailing comma after the "result" parameter. That's fine in JavaScript, but it isn't valid JSON. You can use a tool like https://jsonlint.com/ to verify your JSON is correct.
